name: ez
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  circular_profile_avatar: ^2.0.0
  shared_preferences: ^2.0.15
  progress_dialog: ^1.2.1
  http: ^0.13.5
  fluttertoast: ^8.0.9
  bottom_navy_bar: ^5.4.0
  cached_network_image: ^3.1.0
  flutter_svg: ^1.1.5
  flutter_rating_bar: ^3.0.1+1
  country_code_picker: ^2.0.1
  intl:
  url_launcher: ^5.3.0
  country_picker: ^2.0.19
  flutter_linkify: ^3.1.0
  carousel_pro: ^1.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  maps_launcher: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  share: ^0.6.4+2
  flutter_google_places: ^0.3.0
  #webview_flutter: ^0.3.21
  location: ^4.4.0
  flutter_screenutil: ^0.4.2
  line_icons: ^0.2.0
  google_maps_place_picker_mb:
  google_maps_flutter:
  dotted_border: ^2.0.0+2
  scrollable_positioned_list: ^0.1.7
  image_picker: ^0.8.5+3
  date_picker_timeline: ^1.2.1
  chips_choice: ^2.0.1
  dots_indicator: ^1.0.0
  flutter_html:
  carousel_slider: ^2.2.1
  table_calendar: ^2.3.0
  google_fonts:
  dio: ^4.0.6
  razorpay_flutter: ^1.2.2
  dotted_line: ^2.0.2
  flutter_image_slideshow: ^0.1.0
  fancy_drawer: ^1.0.0
  permission_handler: 10.4.0
  #  place_picker:
  photo_view: 0.14.0
  provider: ^6.0.1
  another_flushbar: ^1.10.10
  google_sign_in: ^5.0.4
  firebase_messaging:
  rflutter_alert: ^1.0.3
  firebase_auth: ^3.9.0
  firebase_storage:
#  flutter_local_notifications:
  flutter_local_notifications: ^9.8.0+1
  mask_text_input_formatter: ^1.0.4
  flutter_credit_card: ^0.1.3
  timeago: ^3.1.0
  font_awesome_flutter: ^9.1.0
  firebase_core: ^1.22.0
  cloud_firestore:
  otp_text_field: ^1.1.2
  time_picker_widget: ^1.0.0+10
  firebase_core_platform_interface: 4.5.1
  flutter_login_facebook:
  currency_picker: 2.0.11
dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path:    "assets/images/logo.png"
  android: true
  ios: true
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/mapStyle/map_style.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:  
    
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf 

    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSansBold.ttf 

    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSansRegular.ttf       

    - family: MuliBold
      fonts:
        - asset: assets/fonts/MuliBold.ttf  

    - family: MuliRegular
      fonts:
        - asset: assets/fonts/MuliRegular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf  
   
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
